remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Menu
navigation:
  - title: Accueil
    url: index.md
  - title: Projets
    url: projets.md
  - title: Réflexion
    url: reflexion.md
  - title: Carrière
    url: carriere.md
  - title: CSR
    url: csr.md
  - title: Mobilité
    url: mobilite.md
  - title: Contact
    url: contact.md
